# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bot.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='bot.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\tbot.proto\"\r\n\x0bNullRequest\"\x0e\n\x0cNullResponse\"$\n\x0e\x43hannelRequest\x12\x12\n\nchannel_id\x18\x01 \x01(\x03\",\n\rOptionMessage\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x98\x01\n\x13\x41llSettingsResponse\x12;\n\x0c\x61ll_settings\x18\x01 \x03(\x0b\x32%.AllSettingsResponse.AllSettingsEntry\x1a\x44\n\x10\x41llSettingsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1f\n\x05value\x18\x02 \x01(\x0b\x32\x10.SettingResponse:\x02\x38\x01\"\x95\x01\n\x0fSettingResponse\x12\x12\n\nowner_name\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x15\n\rdefault_value\x18\x03 \x01(\t\x12\x16\n\x0ewrite_defaults\x18\x04 \x01(\x08\x12\r\n\x05scope\x18\x05 \x01(\t\x12\x14\n\x0csetting_type\x18\x06 \x01(\t\x12\x0c\n\x04help\x18\x07 \x01(\t2u\n\x03\x42ot\x12\x34\n\x0freload_settings\x12\x0f.ChannelRequest\x1a\x0e.OptionMessage\"\x00\x12\x38\n\x10get_all_settings\x12\x0c.NullRequest\x1a\x14.AllSettingsResponse\"\x00\x62\x06proto3'
)




_NULLREQUEST = _descriptor.Descriptor(
  name='NullRequest',
  full_name='NullRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=13,
  serialized_end=26,
)


_NULLRESPONSE = _descriptor.Descriptor(
  name='NullResponse',
  full_name='NullResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=42,
)


_CHANNELREQUEST = _descriptor.Descriptor(
  name='ChannelRequest',
  full_name='ChannelRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='channel_id', full_name='ChannelRequest.channel_id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=80,
)


_OPTIONMESSAGE = _descriptor.Descriptor(
  name='OptionMessage',
  full_name='OptionMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ok', full_name='OptionMessage.ok', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='message', full_name='OptionMessage.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=126,
)


_ALLSETTINGSRESPONSE_ALLSETTINGSENTRY = _descriptor.Descriptor(
  name='AllSettingsEntry',
  full_name='AllSettingsResponse.AllSettingsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='AllSettingsResponse.AllSettingsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='AllSettingsResponse.AllSettingsEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=213,
  serialized_end=281,
)

_ALLSETTINGSRESPONSE = _descriptor.Descriptor(
  name='AllSettingsResponse',
  full_name='AllSettingsResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='all_settings', full_name='AllSettingsResponse.all_settings', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_ALLSETTINGSRESPONSE_ALLSETTINGSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=129,
  serialized_end=281,
)


_SETTINGRESPONSE = _descriptor.Descriptor(
  name='SettingResponse',
  full_name='SettingResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='owner_name', full_name='SettingResponse.owner_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='SettingResponse.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='default_value', full_name='SettingResponse.default_value', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='write_defaults', full_name='SettingResponse.write_defaults', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='scope', full_name='SettingResponse.scope', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='setting_type', full_name='SettingResponse.setting_type', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='help', full_name='SettingResponse.help', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=284,
  serialized_end=433,
)

_ALLSETTINGSRESPONSE_ALLSETTINGSENTRY.fields_by_name['value'].message_type = _SETTINGRESPONSE
_ALLSETTINGSRESPONSE_ALLSETTINGSENTRY.containing_type = _ALLSETTINGSRESPONSE
_ALLSETTINGSRESPONSE.fields_by_name['all_settings'].message_type = _ALLSETTINGSRESPONSE_ALLSETTINGSENTRY
DESCRIPTOR.message_types_by_name['NullRequest'] = _NULLREQUEST
DESCRIPTOR.message_types_by_name['NullResponse'] = _NULLRESPONSE
DESCRIPTOR.message_types_by_name['ChannelRequest'] = _CHANNELREQUEST
DESCRIPTOR.message_types_by_name['OptionMessage'] = _OPTIONMESSAGE
DESCRIPTOR.message_types_by_name['AllSettingsResponse'] = _ALLSETTINGSRESPONSE
DESCRIPTOR.message_types_by_name['SettingResponse'] = _SETTINGRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NullRequest = _reflection.GeneratedProtocolMessageType('NullRequest', (_message.Message,), {
  'DESCRIPTOR' : _NULLREQUEST,
  '__module__' : 'bot_pb2'
  # @@protoc_insertion_point(class_scope:NullRequest)
  })
_sym_db.RegisterMessage(NullRequest)

NullResponse = _reflection.GeneratedProtocolMessageType('NullResponse', (_message.Message,), {
  'DESCRIPTOR' : _NULLRESPONSE,
  '__module__' : 'bot_pb2'
  # @@protoc_insertion_point(class_scope:NullResponse)
  })
_sym_db.RegisterMessage(NullResponse)

ChannelRequest = _reflection.GeneratedProtocolMessageType('ChannelRequest', (_message.Message,), {
  'DESCRIPTOR' : _CHANNELREQUEST,
  '__module__' : 'bot_pb2'
  # @@protoc_insertion_point(class_scope:ChannelRequest)
  })
_sym_db.RegisterMessage(ChannelRequest)

OptionMessage = _reflection.GeneratedProtocolMessageType('OptionMessage', (_message.Message,), {
  'DESCRIPTOR' : _OPTIONMESSAGE,
  '__module__' : 'bot_pb2'
  # @@protoc_insertion_point(class_scope:OptionMessage)
  })
_sym_db.RegisterMessage(OptionMessage)

AllSettingsResponse = _reflection.GeneratedProtocolMessageType('AllSettingsResponse', (_message.Message,), {

  'AllSettingsEntry' : _reflection.GeneratedProtocolMessageType('AllSettingsEntry', (_message.Message,), {
    'DESCRIPTOR' : _ALLSETTINGSRESPONSE_ALLSETTINGSENTRY,
    '__module__' : 'bot_pb2'
    # @@protoc_insertion_point(class_scope:AllSettingsResponse.AllSettingsEntry)
    })
  ,
  'DESCRIPTOR' : _ALLSETTINGSRESPONSE,
  '__module__' : 'bot_pb2'
  # @@protoc_insertion_point(class_scope:AllSettingsResponse)
  })
_sym_db.RegisterMessage(AllSettingsResponse)
_sym_db.RegisterMessage(AllSettingsResponse.AllSettingsEntry)

SettingResponse = _reflection.GeneratedProtocolMessageType('SettingResponse', (_message.Message,), {
  'DESCRIPTOR' : _SETTINGRESPONSE,
  '__module__' : 'bot_pb2'
  # @@protoc_insertion_point(class_scope:SettingResponse)
  })
_sym_db.RegisterMessage(SettingResponse)


_ALLSETTINGSRESPONSE_ALLSETTINGSENTRY._options = None

_BOT = _descriptor.ServiceDescriptor(
  name='Bot',
  full_name='Bot',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=435,
  serialized_end=552,
  methods=[
  _descriptor.MethodDescriptor(
    name='reload_settings',
    full_name='Bot.reload_settings',
    index=0,
    containing_service=None,
    input_type=_CHANNELREQUEST,
    output_type=_OPTIONMESSAGE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='get_all_settings',
    full_name='Bot.get_all_settings',
    index=1,
    containing_service=None,
    input_type=_NULLREQUEST,
    output_type=_ALLSETTINGSRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_BOT)

DESCRIPTOR.services_by_name['Bot'] = _BOT

# @@protoc_insertion_point(module_scope)
