# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import bot_pb2 as bot__pb2


class BotStub(object):
    """Describes the bot rpc
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.reload_settings = channel.unary_unary(
                '/Bot/reload_settings',
                request_serializer=bot__pb2.ChannelRequest.SerializeToString,
                response_deserializer=bot__pb2.OptionMessage.FromString,
                )
        self.get_all_settings = channel.unary_unary(
                '/Bot/get_all_settings',
                request_serializer=bot__pb2.NullRequest.SerializeToString,
                response_deserializer=bot__pb2.AllSettingsResponse.FromString,
                )


class BotServicer(object):
    """Describes the bot rpc
    """

    def reload_settings(self, request, context):
        """Returns all the help the bot has.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_all_settings(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BotServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'reload_settings': grpc.unary_unary_rpc_method_handler(
                    servicer.reload_settings,
                    request_deserializer=bot__pb2.ChannelRequest.FromString,
                    response_serializer=bot__pb2.OptionMessage.SerializeToString,
            ),
            'get_all_settings': grpc.unary_unary_rpc_method_handler(
                    servicer.get_all_settings,
                    request_deserializer=bot__pb2.NullRequest.FromString,
                    response_serializer=bot__pb2.AllSettingsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Bot', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Bot(object):
    """Describes the bot rpc
    """

    @staticmethod
    def reload_settings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Bot/reload_settings',
            bot__pb2.ChannelRequest.SerializeToString,
            bot__pb2.OptionMessage.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get_all_settings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Bot/get_all_settings',
            bot__pb2.NullRequest.SerializeToString,
            bot__pb2.AllSettingsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
